package com.stepstonks.app.domain.model

enum class ForumCategory(val label: String, val emoji: String) {
    ALL("All Posts", "🌐"),
    GENERAL("General", "💬"),
    TIPS("Tips & Tricks", "💡"),
    TRADING("STK Trading", "📈"),
    ACHIEVEMENTS("Achievements", "🏆"),
    GUIDES("Guides", "📖")
}

data class ForumPost(
    val id: String,
    val authorId: String,
    val authorName: String,
    val title: String,
    val content: String,
    val category: ForumCategory,
    val likes: Int = 0,
    val commentCount: Int = 0,
    val timestamp: Long = System.currentTimeMillis(),
    val tags: List<String> = emptyList(),
    val isLiked: Boolean = false,
    val isPinned: Boolean = false
)

val MOCK_FORUM_POSTS = listOf(
    ForumPost("1", "u1", "CryptoWalker",
        "GUIDE: How I earned 500 STK in one week!",
        "After 7 days of consistent walking with my Epic sneaker equipped, here's my complete strategy breakdown. The key is stacking streak bonuses with challenge completions...",
        ForumCategory.GUIDES, likes = 342, commentCount = 67,
        timestamp = System.currentTimeMillis() - 86_400_000L * 2,
        tags = listOf("guide", "strategy", "sneakers"), isPinned = true),
    ForumPost("2", "u2", "NeonStrider",
        "Legendary sneaker prices dropping 15% — time to buy? 📉",
        "Looking at STK market trends this week, Legendary sneaker floor prices have dropped significantly. Here's my analysis of whether this is a dip to buy or a trend to avoid...",
        ForumCategory.TRADING, likes = 128, commentCount = 43,
        timestamp = System.currentTimeMillis() - 3_600_000L * 5,
        tags = listOf("trading", "legendary", "market")),
    ForumPost("3", "u3", "StepstonksPro",
        "🎉 Achievement Unlocked: 1,000,000 Steps!",
        "After 3 months of daily walks, I finally hit the one million step milestone! Here's everything I learned about the game mechanics along the way...",
        ForumCategory.ACHIEVEMENTS, likes = 891, commentCount = 134,
        timestamp = System.currentTimeMillis() - 3_600_000L * 8,
        tags = listOf("achievement", "milestone", "1m")),
    ForumPost("4", "u4", "WalkToEarn99",
        "Best urban walking routes to maximize steps per hour",
        "I've tested 20+ routes in my city over 6 weeks. Here are the top 5 for pure step count, plus tips on avoiding traffic light delays that kill your rhythm...",
        ForumCategory.TIPS, likes = 256, commentCount = 89,
        timestamp = System.currentTimeMillis() - 86_400_000L,
        tags = listOf("tips", "routes", "urban")),
    ForumPost("5", "u5", "TokenHunter",
        "Energy system explained — the full formula revealed 🔋",
        "After 2 weeks of data collection I cracked the energy refill formula. It's not linear like most people think. Here's the actual equation and how to optimize around it...",
        ForumCategory.TIPS, likes = 445, commentCount = 201,
        timestamp = System.currentTimeMillis() - 86_400_000L * 3,
        tags = listOf("energy", "mechanics", "formula")),
    ForumPost("6", "u6", "CryptoFitness",
        "Weekly vs Daily challenges: which gives more STK per step?",
        "I calculated the actual STK per step ratio across challenge types. The results might surprise you — weekly challenges have a hidden multiplier most people miss...",
        ForumCategory.GENERAL, likes = 89, commentCount = 34,
        timestamp = System.currentTimeMillis() - 3_600_000L * 2,
        tags = listOf("challenges", "math", "efficiency")),
    ForumPost("7", "u7", "BlockchainRunner",
        "New personal record: 35,000 steps in one day! 🏃‍♂️",
        "Pushed my limits with Legendary sneaker equipped. Started at 5am and walked until sunset. The earning rate at that step count was absolutely insane...",
        ForumCategory.ACHIEVEMENTS, likes = 567, commentCount = 78,
        timestamp = System.currentTimeMillis() - 3_600_000L * 12,
        tags = listOf("record", "legendary", "grind")),
    ForumPost("8", "u8", "MoonWalker_X",
        "Referral program deep dive — I earned 1000 STK just from inviting friends",
        "Here's my referral strategy that generated 1000 STK in month one without walking a single extra step. The compounding bonus structure is genius...",
        ForumCategory.GUIDES, likes = 723, commentCount = 156,
        timestamp = System.currentTimeMillis() - 86_400_000L * 4,
        tags = listOf("referral", "passive", "strategy")),
)
